### ISSUE TITLE
Activity pauses when the number in csv is not found in the whatsapp contact list

### ISSUE THREAD

**Issue by skdhruv** [nikhilmuz/WhatsApp-Bulk-Sender#13]

**Comment by nikhilmuz** [comment]
This bug I already have in mind and will be fixed soon. As of now, you have to click OK on the message received by the WhatsApp client. You may validate contacts via WhatsApp database at /data/data/com.whatsapp/[wa.db or msgstore.db]

**Comment by chiaqf** [comment]
Greetings, any update for now?

**Comment by chiaqf** [comment]
I observed that intent will not always open chat to strangers, how about implementing WhatsApp's click to chat feature instead of using intent?

Example : https://api.whatsapp.com/send?phone=

**Comment by nikhilmuz** [comment]
That doesn't allows to send additional information data like images and
videos to be attached to messages which I intend to add later on. BTW you
can add contact and sync to whatsapp in order to insure that the
Conversation activities always opens for stranger.

**Comment by chiaqf** [comment]
List<AccessibilityNodeInfo> nodes = getRootInActiveWindow().findAccessibilityNodeInfosByViewId("com.whatsapp:id/send");
                final List<AccessibilityNodeInfo> nodesback = getRootInActiveWindow().findAccessibilityNodeInfosByViewId("com.whatsapp:id/back");

                for (AccessibilityNodeInfo nodeInfo : nodes) {
                    if (nodeInfo != null) {
                        nodes.get(0).performAction(ACTION_CLICK);
                        Handler handler = new Handler();
                        handler.postDelayed(new Runnable() {
                            public void run() {
                                // Actions to do after 1 seconds
                                for (AccessibilityNodeInfo nodebackInfo : nodesback) {
                                    if(nodebackInfo!=null){
                                        nodesback.get(0).performAction(ACTION_CLICK);
                                    }
                                }
                            }
                        }, 1000);

                        break;
                    }
                }


I managed to do this

**Comment by nikhilmuz** [comment]
Thanks for the codes. I will look into it and update accordingly. Thanks
again for showing interest in contributing to this repo.

**Comment by chiaqf** [comment]
You're welcome, thanks for sharing these too. Glad to help

**Comment by nikhilmuz** [comment]
@chiaqf marked your concern as a new issue and I will rectify it separately meanwhile I am closing this issue after a PR resolving the concern of @skdhruv
