### ISSUE TITLE
whatsapp is not install

### ISSUE THREAD

**Issue by tayyab18** [nikhilmuz/WhatsApp-Bulk-Sender#14]

**Comment by tayyab18** [comment]
it is showing error after uploading file

**Comment by nikhilmuz** [comment]
please check if the file is valid csv in the instructed format in readme. I will also try to handle this error

**Comment by tayyab18** [comment]
please upload s sample file

Thanks

**Comment by mmjbisnis** [comment]
same with me, please uploads a sample file

thanks

**Comment by nikhilmuz** [comment]
Sample already updated refer readme

**Comment by nikhilmuz** [comment]
@tayyab18 check whether whatsapp client is installed or not. If yes, check for csv file if it is in format mentioned in readme. If issue exists reopen this issue.
