### ISSUE TITLE
Error to send

### ISSUE THREAD

**Issue by eduardofiorini** [nikhilmuz/WhatsApp-Bulk-Sender#18]
Hi, Congratulations on the project, I can not make it work on Android 6 and 8 and on WhatsApp Normal and Business, it gives an error and closes when clicking send. Does the cell phone need to be rooted?

**Comment by nikhilmuz** [comment]
Not actually, because it uses accessibility permissions in case of unrooted phones. It would be better if you describe more about the error you are getting. If possible logcat or screenshot is more helpful.

**Comment by mubi64** [comment]
Hi, I am facing the same issue. Here are the screen shots.

![screenshot_20190305-142747](https://user-images.githubusercontent.com/17858365/53795123-1e9dbc00-3f53-11e9-8b3e-d53d7eca952f.png)
![screenshot_20190305-142738](https://user-images.githubusercontent.com/17858365/53795125-1e9dbc00-3f53-11e9-8dc7-07cc65eead6e.png)

**Comment by nikhilmuz** [comment]
Will you be able to provide the logs also? It would be easier to reproduce
the same and debug then.

**Comment by 9804701373** [comment]
After press button send . It just off app.  O uaed mi p2 . Handset .android 5.1.1

**Comment by 9804701373** [comment]
I got  error on chrome extension after loading pop-up . It's not open upload button

**Comment by nikhilmuz** [comment]
Though it should not be the case, you may share the error message you are
getting.

**Comment by nikhilmuz** [comment]
The extension won't work on recent version of whatsapp web. I will try to
fix this.

**Comment by 9804701373** [comment]
Yess it's show me error message unfortunately . WhatsApp Sender has stopped.  And apps go to off

**Comment by nikhilmuz** [comment]
@9804701373 The android app is working fine. You must have done something wrong following the Readme file. Specifically CSV file. @eduardofiorini @mubi64
