### ISSUE TITLE
Upload button not functioning as in the select file pop up does not show in the chrome extension

### ISSUE THREAD

**Issue by Hussain525321** [nikhilmuz/WhatsApp-Bulk-Sender#20]
.

**Comment by Hussain525321** [comment]
Upload button in the chrome extension is not functioning as in the select file from PC pop up does not show up
<img width="291" alt="Screen Shot 2019-05-31 at 1 05 54 PM" src="https://user-images.githubusercontent.com/35068531/58689526-df8dd400-83a4-11e9-80d4-bb7a1b612117.png">

**Comment by nikhilmuz** [comment]
It works for me. It won't work on pages and tabs different than web.whatsapp.com that too when logged in. If already logged in and on the whatsapp web page, try reloading the page once. P. S. If above option doesn't helps, try updating chrome to latest version. If it still doesn't works try installing it in different chrome profile.

**Comment by rkwhatelse** [comment]
Hi Nikhil,
I find the same error (upload button is getting failed). 
* Reloaded whatsapp web page
* Tried with and without profile with multiple users.
* Updated new chrome browser

No action occurs after clicking upload of whatsapp bulk sender

**Comment by nikhilmuz** [comment]
Thanks for letting me know I am on it to analyze the issue. Meanwhile you
may share error if any, that would be really appriciated.

**Comment by Hussain525321** [comment]
No such error in console, basically the button is clickable but the action of file select pop up coming up does not work.

**Comment by nikhilmuz** [comment]
Will look into it. Thanks for updating.

**Comment by nikhilmuz** [comment]
Refer commit [768b09657dfcfd2edc663f9456ca1602a0e21fc0](https://github.com/nikhilmuz/WhatsApp-Bulk-Sender/commit/768b09657dfcfd2edc663f9456ca1602a0e21fc0) Deprecated in latest Chrome. Last worked on version: [74.0.3729.108].
I will try to rewrite it for recent version.

**Comment by Hussain525321** [comment]
Do you have 74.0.3729.108 of chrome for mac?
Can you share a download link of the specified version?
