### ISSUE TITLE
Query : Can we send images and videos with chrome extension

### ISSUE THREAD

**Issue by bhavyaw** [nikhilmuz/WhatsApp-Bulk-Sender#21]
@nikhilmuz,

Just a simple query : 

Can we send images and videos with the chrome extension ?

**Comment by nikhilmuz** [comment]
Not yet but the feature is yet to be implemented. You can programmatically
send via console but UI implementation is pending.

**Comment by nikhilmuz** [comment]
Update: The chrome extension is depricated in current version of WhatsApp Web. I will try fixing it. Refer readme for more details.
