### ISSUE TITLE
Whatsapp not installed

### ISSUE THREAD

**Issue by amin101** [nikhilmuz/WhatsApp-Bulk-Sender#31]
I'm trying to run the app on NOX emulator. but i receive `Whatsapp not installed` message after click send. BTW NOX has root option and it is enabled. 
NOX player 6.6.0.2
whatsapp 2.20.27

**Comment by nikhilmuz** [comment]
I guess default WhatsApp variant for root node is WhatsApp business. Try running in non root node or installing WhatsApp business and re-update this issue if problem still exists

**Comment by amin101** [comment]
whatsapp business resolve the issue but even after `Task completed` i have no message on receiver devices

**Comment by nikhilmuz** [comment]
Make sure WhatsApp business is registered. If still, it doesn't work maybe there is a package name wrongly written in code. Try using non-root method in such case i.e. don't give superuser permission to the app. P.S. Root method is not recommended as it gets detected by WhatsApp and the account gets blocked automatically.
