### ISSUE TITLE
WhatsApp Type?

### ISSUE THREAD

**Issue by DeLuca92** [nikhilmuz/WhatsApp-Bulk-Sender#36]
This apk is for normal whatsapp or business?
I need to compile android studio?
Because the apk is 2 years ago and the last update is 23 days
Thx

**Comment by nikhilmuz** [comment]
That's the change in rooted version which was commited recently. Anyway
it's for normal WhatsApp. For using it on WhatsApp Business, Refactor
package name and activity name hard coded in codebase.

**Comment by DeLuca92** [comment]
@nikhilmuz , and u implementing send image or gifs?

**Comment by nikhilmuz** [comment]
I am not working on this project since very long. I will be adding such features if in future I am able to devote time on this. As of now there is no such support for media.

**Comment by DeLuca92** [comment]
ahh, okays.
I will create this :)

**Comment by nikhilmuz** [comment]
Thanks for showing interest in contributing. Feel free to submit PR referencing #22. I will be happy to merge.
