### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by premod** [nikhilmuz/WhatsApp-Bulk-Sender#39]
upload  not working ,nikhil

**Comment by nikhilmuz** [comment]
Can you be a bit specific in this regard?

**Comment by premod** [comment]
while using chrome extension in web.whatsapp.com.
for uploading the json data, clicking the upload button not doing any response

**Comment by nikhilmuz** [comment]
Hi! @premod chrome extension is currently deprecated after recent changes from WhatsApp end. Refer readme to know more. Feel free to submit PR incase you are able to resolve it. :blush:

**Comment by alwinsajip** [comment]
Could you please tell me how to fix it
